[project]
name = "expense-tracker-cli"
version = "0.1.0"
description = "Simple cli expense tracker application to manage your finances"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
exp = "app_.main:main"